package com.github.yuttyann.scriptblockplus.type;

public enum ClickType {
	INTERACT_CREATE("INTERACT_SCRIPTBLOCKPLUS_CREATECLICK"),
	INTERACT_ADD("INTERACT_SCRIPTBLOCKPLUS_ADDCLICK"),
	INTERACT_REMOVE("INTERACT_SCRIPTBLOCKPLUS_REMOVECLICK"),
	INTERACT_VIEW("INTERACT_SCRIPTBLOCKPLUS_VIEWCLICK"),
	WALK_CREATE("WALK_SCRIPTBLOCKPLUS_CREATECLICK"),
	WALK_ADD("WALK_SCRIPTBLOCKPLUS_ADDCLICK"),
	WALK_REMOVE("WALK_SCRIPTBLOCKPLUS_REMOVECLICK"),
	WALK_VIEW("WALK_SCRIPTBLOCKPLUS_VIEWCLICK");

	private String type;

	private ClickType(String type) {
		this.type = type;
	}

	@Override
	public String toString() {
		return type;
	}
}
